### ISSUE TITLE
Document that file_extension and file_prefix can also be supplied as regular expression

### ISSUE THREAD

**Issue by julianrubisch** [danmayer/churn#74]
I was going to suggest enabling regexes for `file_extension` and `file_prefix`, when I realized it already supports that.

I think this should go into the README. Give me a ping if I should prepare a PR.

**Comment by danmayer** [comment]
sure if you could send a README PR that would be great. I kept this open thinking I could do that soon, but I haven't been working much on churn for awhile, and I think the docs might turn out better if written from the perspective of a user. Let me know if you are still interested in updating the docs @julianrubisch
