### ISSUE TITLE
Feature request: Add support for json output

### ISSUE THREAD

**Issue by berlin-ab** [danmayer/churn#86]
I just stumbled on your library. It works great for quick analysis, except when I was trying to extract a JSON version of the data to compare with another set of data I have from another tool. I then tried to use the `yq` tool to transform the YAML output into JSON, but the keys printed in the YAML output are symbols, which makes the JSON awkward to use.

There are really two suggestions here:

1. Print string keys instead of symbol keys when printing the YAML
2. Provide a print as JSON feature

**Comment by danmayer** [comment]
II don't work on this library much anymore, but If anyone wants to take it on I would take a PR adding JSON output or any other formats

**Comment by etagwerker** [comment]
I took a stab at this because it could be useful for something I'm working on.
